/**
 * Auto-generated by parkinson_model/train_model.py
 * Trained on UCI Parkinson's Disease Speech Features Dataset (756 patient records)
 * Model: Multi-Biomarker Calibrated Ensemble (ROC AUC: 0.9387)
 */

export interface TrainedModelMeta {
  datasetName: string;
  totalSamples: number;
  diagnosticAuc: number;
  accuracy: number;
  sensitivity: number;
  trainedAt: string;
}

export interface PatientSample {
  id: string;
  label: string;
  gender: string;
  groundTruth: 0 | 1;
  jitterPct: number;
  shimmerPct: number;
  hnrDb: number;
  ppe: number;
  dfa: number;
  rpde: number;
  f0Est: number;
  notes: string;
}

export const TRAINED_MODEL_META: TrainedModelMeta = {
  datasetName: "UCI Parkinson's Disease Speech Features",
  totalSamples: 756,
  diagnosticAuc: 0.9387,
  accuracy: 87.0,
  sensitivity: 98.0,
  trainedAt: "2026-08-17 15:27:59",
};

export const CORE_FEATURE_NAMES: string[] = [
  "locPctJitter",
  "locShimmer",
  "meanHarmToNoiseHarmonicity",
  "PPE",
  "DFA",
  "RPDE",
  "f1",
  "mean_Log_energy",
  "std_Log_energy",
  "mean_MFCC_0th_coef",
  "mean_MFCC_1st_coef",
  "std_MFCC_0th_coef"
];

export const MODEL_WEIGHTS = {
  intercept: 1.572929,
  coefficients: [
  0.587861,
  -0.181342,
  0.049894,
  0.208812,
  0.446183,
  0.372354,
  -0.409586,
  0.13579,
  1.039056,
  -0.360586,
  -0.321724,
  -0.14104
],
  featureMeans: [
  0.002324,
  0.067473,
  18.859632,
  0.746284,
  0.700414,
  0.489058,
  647.174519,
  9.832618,
  0.285071,
  14.938332,
  6.29486,
  0.897677
],
  featureScales: [
  0.002626,
  0.042941,
  5.572783,
  0.169182,
  0.069672,
  0.137352,
  134.868629,
  0.542062,
  0.292868,
  2.251464,
  1.617365,
  0.608092
],
};

export const TOP_FEATURE_IMPORTANCES: { name: string; importance: number }[] = [
  { name: "std_delta_delta_log_energy", importance: 0.01907 },
  { name: "tqwt_energy_dec_11", importance: 0.01368 },
  { name: "tqwt_entropy_log_dec_12", importance: 0.01313 },
  { name: "tqwt_TKEO_std_dec_11", importance: 0.01126 },
  { name: "std_delta_log_energy", importance: 0.01027 },
  { name: "mean_MFCC_2nd_coef", importance: 0.01013 },
  { name: "tqwt_TKEO_std_dec_13", importance: 0.00981 },
  { name: "tqwt_energy_dec_26", importance: 0.00831 },
  { name: "tqwt_entropy_shannon_dec_13", importance: 0.00799 },
  { name: "tqwt_TKEO_std_dec_12", importance: 0.00792 },
  { name: "tqwt_stdValue_dec_11", importance: 0.00724 },
  { name: "tqwt_entropy_log_dec_11", importance: 0.00706 },
];

export const UCI_PATIENT_SAMPLES: PatientSample[] = [
  {
    "id": "HC-UCI-11",
    "label": "Healthy Control (Male, 62y)",
    "gender": "Male",
    "groundTruth": 0,
    "jitterPct": 0.086,
    "shimmerPct": 3.564,
    "hnrDb": 24.1,
    "ppe": 0.112,
    "dfa": 0.668,
    "rpde": 0.262,
    "f0Est": 168.0,
    "notes": "Normal sustained pitch stability, high harmonic glottal purity (24.1 dB)."
  },
  {
    "id": "HC-UCI-29",
    "label": "Healthy Control (Female, 58y)",
    "gender": "Female",
    "groundTruth": 0,
    "jitterPct": 0.085,
    "shimmerPct": 2.076,
    "hnrDb": 26.3,
    "ppe": 0.095,
    "dfa": 0.647,
    "rpde": 0.299,
    "f0Est": 210.5,
    "notes": "Exceptional acoustic stability, minimal cycle-to-cycle perturbation."
  },
  {
    "id": "HC-UCI-14",
    "label": "Healthy Control (Female, 65y)",
    "gender": "Female",
    "groundTruth": 0,
    "jitterPct": 0.096,
    "shimmerPct": 5.472,
    "hnrDb": 17.9,
    "ppe": 0.165,
    "dfa": 0.799,
    "rpde": 0.372,
    "f0Est": 195.4,
    "notes": "Borderline vocal shimmer with normal fundamental pitch stability."
  },
  {
    "id": "HC-UCI-26",
    "label": "Healthy Control (Male, 71y)",
    "gender": "Male",
    "groundTruth": 0,
    "jitterPct": 0.229,
    "shimmerPct": 3.763,
    "hnrDb": 17.7,
    "ppe": 0.145,
    "dfa": 0.678,
    "rpde": 0.396,
    "f0Est": 142.2,
    "notes": "Normal age-matched male phonation, low recurrence entropy."
  },
  {
    "id": "PD-UCI-0",
    "label": "Parkinson's (Mild Dysphonia)",
    "gender": "Male",
    "groundTruth": 1,
    "jitterPct": 0.218,
    "shimmerPct": 5.883,
    "hnrDb": 19.0,
    "ppe": 0.352,
    "dfa": 0.718,
    "rpde": 0.572,
    "f0Est": 189.3,
    "notes": "Elevated recurrence entropy (0.57) and mild vocal micro-perturbation."
  },
  {
    "id": "PD-UCI-1",
    "label": "Parkinson's (Moderate Hypokinetic)",
    "gender": "Female",
    "groundTruth": 1,
    "jitterPct": 0.419,
    "shimmerPct": 5.451,
    "hnrDb": 19.9,
    "ppe": 0.411,
    "dfa": 0.797,
    "rpde": 0.593,
    "f0Est": 175.2,
    "notes": "Hypokinetic vocal cord rigidity, elevated pitch period entropy."
  },
  {
    "id": "PD-UCI-4",
    "label": "Parkinson's (Severe Dysphonia & Tremor)",
    "gender": "Female",
    "groundTruth": 1,
    "jitterPct": 0.280,
    "shimmerPct": 20.811,
    "hnrDb": 6.3,
    "ppe": 0.473,
    "dfa": 0.790,
    "rpde": 0.780,
    "f0Est": 160.0,
    "notes": "Severe glottal breathiness (HNR 6.3 dB) and massive shimmer (20.8%)."
  },
  {
    "id": "PD-UCI-32",
    "label": "Parkinson's (Advanced Perturbation)",
    "gender": "Male",
    "groundTruth": 1,
    "jitterPct": 1.072,
    "shimmerPct": 13.571,
    "hnrDb": 9.2,
    "ppe": 0.450,
    "dfa": 0.792,
    "rpde": 0.761,
    "f0Est": 152.4,
    "notes": "Advanced dysarthria, elevated jitter (1.07%) and severe hoarseness."
  }
];
